# Generated by Django 4.0.2 on 2022-07-13 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 14, 15, 58, 818607, tzinfo=utc)),
        ),
    ]
